name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  release:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.image }}
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@90fe0da793883e878fa0a09ac2979190074920c4 # v1.67.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUNDLE: AppImage
          PACKAGES: |
            packages.${{ steps.init.outputs.system }}.default
            images.${{ steps.init.outputs.system }}.default
